uploads = []
generated = []

[[outputs]]
id = "k-dw4wydOUw_tkdr4zQoy"
uri = "file://output/001/avatar.png"
type = "image"
title = "User 001 — PuLID Avatar"

[[outputs]]
id = "rWzdPTK9_HDrRD3WItRx_"
uri = "file://output/001/avatar_outfit.png"
type = "image"
title = "User 001 — Outfit"

[[outputs]]
id = "ZBYZZ-9cFWMhkqR_SVJH8"
uri = "file://output/002/avatar.png"
type = "image"
title = "User 002 — PuLID Avatar"

[[outputs]]
id = "fVjeTHAdWqCzUqZgNyabp"
uri = "file://output/002/avatar_outfit.png"
type = "image"
title = "User 002 — Outfit"

[[outputs]]
id = "Sv-lBJ194TWQzBP47DN5Y"
uri = "file://output/003/avatar.png"
type = "image"
title = "User 003 — PuLID Avatar"

[[outputs]]
id = "6iT7juD_zrERDuXhnEw7k"
uri = "file://output/003/avatar_outfit.png"
type = "image"
title = "User 003 — Outfit"

[[outputs]]
id = "UBeTBAWrMfwuATccYIMNu"
uri = "file://output/004/avatar.png"
type = "image"
title = "User 004 — PuLID Avatar"

[[outputs]]
id = "7eyZGJALJzy0GO9Zy8edB"
uri = "file://output/004/avatar_outfit.png"
type = "image"
title = "User 004 — Outfit"
